// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoMO3m6IzaVZDM8c5ayWuooqJdRP5fQIk',
    appId: '1:296913940818:web:3c600f81d52db5766e0a8b',
    messagingSenderId: '296913940818',
    projectId: 'utfpr-iot-trabalho-final',
    authDomain: 'utfpr-iot-trabalho-final.firebaseapp.com',
    databaseURL: 'https://utfpr-iot-trabalho-final-default-rtdb.firebaseio.com',
    storageBucket: 'utfpr-iot-trabalho-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGwAIZNJ3fxfSWPj7uvGOmJmn7bAMJQL0',
    appId: '1:296913940818:android:77cf95ec160071f46e0a8b',
    messagingSenderId: '296913940818',
    projectId: 'utfpr-iot-trabalho-final',
    databaseURL: 'https://utfpr-iot-trabalho-final-default-rtdb.firebaseio.com',
    storageBucket: 'utfpr-iot-trabalho-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUi-qrnkVbCMq56eJLepPLM1KBbZzdAgE',
    appId: '1:296913940818:ios:717ed90168433d6f6e0a8b',
    messagingSenderId: '296913940818',
    projectId: 'utfpr-iot-trabalho-final',
    databaseURL: 'https://utfpr-iot-trabalho-final-default-rtdb.firebaseio.com',
    storageBucket: 'utfpr-iot-trabalho-final.firebasestorage.app',
    iosBundleId: 'com.example.iotMonitorApp',
  );
}
